---
- name: Create company shortcode OU
  microsoft.ad.ou:
    name: '{{ company_shortcode }}'
    path: '{{ base_dn }}'
    state: '{{ ou_state }}'

- name: Create OUs
  block:
    - name: Create sub OUs
      microsoft.ad.ou:
        name: '{{ item }}'
        path: OU={{ company_shortcode }},{{ base_dn }}
        state: present
      loop:
        - Groups
        - Users
        - Computers

    - name: Create Computer OUs
      microsoft.ad.ou:
        name: '{{ item }}'
        path: OU=Computers,OU={{ company_shortcode }},{{ base_dn }}
        state: present
      loop:
        - Servers
        - Workstations

    - name: Create User OUs
      microsoft.ad.ou:
        name: '{{ item }}'
        path: OU=Users,OU={{ company_shortcode }},{{ base_dn }}
        state: present
      loop:
        - System Admins
        - Management
        - Finance
        - HR
        - Service Accounts

    - name: Create Group OUs
      microsoft.ad.ou:
        name: '{{ item }}'
        path: OU=Groups,OU={{ company_shortcode }},{{ base_dn }}
      loop:
        - Folder Groups
        - Roll Groups
        - Drive Groups
        - Sync Groups

    - name: Create Linux OU
      microsoft.ad.ou:
        name: Linux Groups 
        path: OU=Groups,OU={{ company_shortcode }},{{ base_dn }}
      when: create_linux_ou == true

  when: ou_state == 'present'
