---
- name: Create System admins
  microsoft.ad.user:
    name: '{{ item.username }}'
    identity: '{{ item.username }}'
    firstname: '{{ item.firstname }}'
    surname: '{{ item.lastname }}'
    display_name: '{{ item.display_name }}'
    upn: '{{ item.username }}@{{ windows_domain_name }}'
    password: '{{ vault_default_user_password }}'
    update_password: on_create
    path: OU=System Admins,OU=Users,OU={{ company_shortcode }},{{ base_dn }}
    groups:
      set:
        - RG - System Admins
        - Domain Admins
        - Domain Users
  loop: '{{ users_system_admins }}'
  when: users_system_admins is defined

- name: Create Helpdesk admins
  microsoft.ad.user:
    name: '{{ item.username }}'
    identity: '{{ item.username }}'
    firstname: '{{ item.firstname }}'
    surname: '{{ item.lastname }}'
    display_name: '{{ item.display_name }}'
    upn: '{{ item.username }}@{{ windows_domain_name }}'
    password: '{{ vault_default_user_password }}'
    update_password: on_create
    path: OU=Helpdesk Admins,OU=Users,OU={{ company_shortcode }},{{ base_dn }}
    groups:
      set:
        - RG - Helpdesk Admins
        - Domain Users
  loop: '{{ users_helpdesk_admins }}'
  when: users_helpdesk_admins is defined

- name: Create Management users
  microsoft.ad.user:
    name: '{{ item.username }}'
    identity: '{{ item.username }}'
    firstname: '{{ item.firstname }}'
    surname: '{{ item.lastname }}'
    display_name: '{{ item.display_name }}'
    upn: '{{ item.username }}@{{ windows_domain_name }}'
    password: '{{ vault_default_user_password }}'
    update_password: on_create
    path: OU=Management,OU=Users,OU={{ company_shortcode }},{{ base_dn }}
    groups:
      set:
        - RG - Management
        - Domain Users
  loop: '{{ users_management }}'
  when: users_management is defined

- name: Create Finance users
  microsoft.ad.user:
    name: '{{ item.username }}'
    identity: '{{ item.username }}'
    firstname: '{{ item.firstname }}'
    surname: '{{ item.lastname }}'
    display_name: '{{ item.display_name }}'
    upn: '{{ item.username }}@{{ windows_domain_name }}'
    password: '{{ vault_default_user_password }}'
    update_password: on_create
    path: OU=Finance,OU=Users,OU={{ company_shortcode }},{{ base_dn }}
    groups:
      set:
        - RG - Finance
        - Domain Users
  loop: '{{ users_finance }}'
  when: users_finance is defined

- name: Create HR users
  microsoft.ad.user:
    name: '{{ item.username }}'
    identity: '{{ item.username }}'
    firstname: '{{ item.firstname }}'
    surname: '{{ item.lastname }}'
    display_name: '{{ item.display_name }}'
    upn: '{{ item.username }}@{{ windows_domain_name }}'
    password: '{{ vault_default_user_password }}'
    update_password: on_create
    path: OU=HR,OU=Users,OU={{ company_shortcode }},{{ base_dn }}
    groups:
      set:
        - RG - Finance
        - Domain Users
  loop: '{{ users_hr }}'
  when: users_hr is defined
