---
- name: Configure Windows Servers
  hosts: windows_servers
  collections:
    - microsoft.ad
    - ansible.windows
  roles:
    - install-adds
    - create-ous
  tasks:
    - name: Install Zabbix agent 2 MSI
      win_package:
        path: https://cdn.zabbix.com/zabbix/binaries/stable/7.4/7.4.0/zabbix_agent2-7.4.0-windows-amd64-openssl.msi
        state: present
        arguments:
          - SERVER=192.168.1.46
          - LISTENPORT=10050
          - LISTENIP=192.168.1.7
          - HOSTNAME={{ hostname }}

    - name: Ensure C:\Temp exists
      win_file:
        path: C:\Temp
        state: directory

    - name: Copy certificate
      win_copy:
        src: files/root.crt
        dest: C:\Temp\

    - name: Install root certificates
      win_certificate_store:
        path: C:\Temp\root.crt
        store_name: root
        state: present

    - name: Set timezone
      win_timezone:
        timezone: AUS Central Standard Time

    - name: Configure w32tm
      win_powershell:
        script: |
          net stop w32time

          w32tm /config /syncfromflags:manual /manualpeerlist:"0.pool.ntp.org, 1.pool.ntp.org, 2.pool.ntp.org"

          w32tm /config /reliable:yes

          net start w32time

    - name: Create folders
      import_tasks: tasks/create-folders.yml

    - name: Create shares
      import_tasks: tasks/create-shares.yml

    - name: Create groups
      import_tasks: tasks/create-groups.yml

    - name: Create users
      import_tasks: tasks/create-users.yml
