---
- name: Configure Windows Servers
  hosts: windows_servers
  collections:
    - microsoft.ad
    - ansible.windows
  tasks:
    - name: Rename host
      win_hostname:
        name: '{{ hostname }}'
      register: hostname_result
    - name: Reboot if necessary
      win_reboot:
      when: hostname_result.reboot_required

    - name: Create new domain in a new forest on the target host and reboot
      microsoft.ad.domain:
        dns_domain_name: '{{ domain_name }}'
        safe_mode_password: '{{ safe_mode_password }}'
        reboot: true

    - name: Ensure server is a domain controller and reboot if necessary
      microsoft.ad.domain_controller:
        dns_domain_name: '{{ domain_name }}'
        domain_admin_user: 'benny@{{ domain_name }}'
        domain_admin_password: '{{ domain_admin_password }}'
        safe_mode_password: '{{ safe_mode_password }}'
        state: domain_controller
        reboot: true

    # - name: Install Windows ADFS and reboot if necessary
    #   win_feature: 
    #     name: ADFS-Federation
    #     state: present
    #   register: adfs_result
    # - name: Reboot if necessary
    #   win_reboot:
    #   when: adfs_result.reboot_required
