---
- name: Configure Windows Servers
  hosts: windows_servers
  collections:
    - microsoft.ad
    - ansible.windows
  roles:
    - install-adds
    - create-ous
  tasks:
    - name: Install windows_exporter MSI
      win_package:
        path: https://github.com/prometheus-community/windows_exporter/releases/download/v0.30.2/windows_exporter-0.30.2-amd64.msi
        state: absent 
        arguments:
          - ADDLOCAL=FirewallException
          - ENABLED_COLLECTORS=cpu,cs,dns,logical_disk,net,os,process,service,time

    - name: Ensure C:\Temp exists
      win_file:
        path: C:\Temp
        state: directory

    - name: Copy certificate
      win_copy:
        src: files/root.crt
        dest: C:\Temp\

    - name: Install root certificates
      win_certificate_store:
        path: C:\Temp\root.crt
        store_name: root
        state: present

    - name: Ensure C:\Data exists
      win_file:
        path: C:\Data
        state: directory

    - name: Ensure C:\Data children folders exist
      win_file:
        path: C:\Data\{{ item }}
        state: directory
      loop:
        - Corporate
        - Marketing
        - Office Administration
        - Operations Tools
        - Plant Management
        - QLD Financial
        - Security
        - SEQ Management

    - name: Create Data share
      win_share:
        name: Data
        path: C:\Data
        full: Administrators

    # - name: Create groups
    #   import_tasks: tasks/create-groups.yml
    #
    # - name: Create users
    #   import_tasks: tasks/create-users.yml
