---
- name: Configure FortiGate
  hosts: fortigates
  gather_facts: false
  collections:
    - fortinet.fortios
  roles:
    - configure-fortigate-system-interfaces
    - configure-fortigate-firewall-settings
    - configure-fortigate-system-settings
    - configure-fortigate-firewall-policies
