- name: Create roll groups
  microsoft.ad.group:
    identity: '{{ item }}'
    scope: global
    path: OU=Roll Groups,OU=Groups,OU={{ company_shortcode }},{{ base_dn }}
  loop:
    - RG - System Admins
    - RG - Management
    - RG - Finance
    - RG - HR

- name: Create LDAP sync groups
  microsoft.ad.group:
    identity: '{{ item }}'
    scope: global
    path: OU=Sync Groups,OU=Groups,OU={{ company_shortcode }},{{ base_dn }}
  loop:
    - SYNC - Snipe-IT
    - SYNC - Bookstack

- name: Create top level project folder security group
  microsoft.ad.group:
    identity: FG - {{ project_folder_path }}-M
    scope: domainlocal
    path: OU=Folder Groups,OU=Groups,OU={{ company_shortcode }},{{ base_dn }}

- name: Create admin project folder security group
  microsoft.ad.group:
    identity: FG - {{ project_folder_path }}!Admin-M
    scope: domainlocal
    path: OU=Folder Groups,OU=Groups,OU={{ company_shortcode }},{{ base_dn }}

- name: Create commercial project folder security group
  microsoft.ad.group:
    identity: FG - {{ project_folder_path }}!Admin!Commercial-M
    scope: domainlocal
    path: OU=Folder Groups,OU=Groups,OU={{ company_shortcode }},{{ base_dn }}
