api_key: "{{ vault_api_key }}"
ansible_host: 192.168.1.99
ansible_user: ansible
ansible_network_os: fortinet.fortios.fortios
ansible_connection: httpapi
ansible_httpapi_use_ssl: yes
ansible_httpapi_validate_certs: no
ansible_httpapi_port: 8665

hostname: RUB-DRW-FW01
admin_username: radbun
admin_password: "{{ vault_admin_password }}"
customer_code: RUB
