ansible_host: 192.168.1.7
ansible_password: '{{ vault_ansible_password }}'
hostname: MGC-DRW-TMS01

sys_admins:
  - firstname: Ben
    lastname: Harris
    username: ben.harris
    display_name: Ben Harris

  - firstname: John
    lastname: Smith
    username: john.smith
    display_name: John Smith
