---
- name: Archive AZ User
  hosts: localhost
  collections:
    - azure.azcollection
  vars:
    domain_name: megacorp.industries
    first_name: John
    last_name: Smith
  tasks:
    - name: Ensure {{ first_name }} {{ last_name }} is archived
      azure_rm_aduser:
        user_principal_name: '{{ first_name }}.{{ last_name }}@{{ domain_name }}'
        state: present
        account_enabled: False
        display_name: 'Archived - {{ first_name }} {{ last_name }}'
        given_name: '{{ first_name }}'
        surname: '{{ last_name }}'
        mail: '{{ first_name }}.{{ last_name }}@{{ domain_name }}'
        mail_nickname: '{{ first_name }}.{{ last_name }}'
