ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore

# Basic Authentication
# ansible_winrm_transport: basic
# ansible_user: Administrator

# Kerberos Authentication
ansible_winrm_transport: kerberos
ansible_user: administrator@PROD.MEGACORP.INDUSTRIES
