ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore

# Basic Authentication
ansible_winrm_transport: basic
ansible_user: Administrator

# Kerberos Authentication
# ansible_winrm_transport: kerberos
# ansible_user: Administrator@MEGACORP.INDUSTRIES

domain_admin_password: '{{ vault_domain_admin_password }}'
safe_mode_password: '{{ vault_safe_mode_password }}'
windows_domain_name: prod.megacorp.industries
