ansible_connection: winrm
# ansible_winrm_transport: basic
ansible_winrm_transport: kerberos
ansible_winrm_server_cert_validation: ignore

domain_admin_password: '{{ vault_domain_admin_password }}'
safe_mode_password: '{{ vault_safe_mode_password }}'
domain_name: megacorp.industries
