---
- name: Configure log memory setting
  fortios_log_memory_setting:
    access_token: '{{ api_key }}'
    vdom:  '{{ vdom }}'
    log_memory_setting:
      status: enable

- name: Configure log null device setting
  fortios_log_null_device_setting:
    access_token: '{{ api_key }}'
    vdom:  '{{ vdom }}'
    log_null_device_setting:
      status: disable

- name: Configure log settings
  fortios_log_setting:
    vdom:  '{{ vdom }}'
    access_token: '{{ api_key }}'
    log_setting:
      resolve_ip: enable
      fwpolicy_implicit_log: enable
      local_in_allow: enable
      local_in_deny_unicast: enable
      local_in_deny_broadcast: enable
      local_out: enable

- name: Configure log memory filter
  fortios_log_memory_filter:
    access_token: '{{ api_key }}'
    vdom:  '{{ vdom }}'
    log_memory_filter:
      severity: information
      local_traffic: enable
