---
- name: Configure email server
  fortios_system_email_server:
    access_token: '{{ api_key }}'
    vdom:  '{{ vdom }}'
    system_email_server:
      reply_to: '{{ email_server_reply_to_address }}'
      server: notification.fortinet.net
      port: 465
      security: smtps
