---
- name: Create INTRA-DENY-untrust-to-untrust policy
  fortios_firewall_policy:
    access_token: '{{ api_key }}'
    state: present
    vdom:  '{{ vdom }}'
    firewall_policy:
      policyid: 10
      name: INTRA-DENY-untrust-to-untrust
      status: enable
      srcintf:
        - name: z-untrust
      dstintf:
        - name: z-untrust
      action: deny
      srcaddr:
        - name: all
      dstaddr:
        - name: all
      internet_service: disable
      internet_service_src: disable
      schedule: always
      service: 
        - name: ALL
      logtraffic: all
      np_acceleration: enable
      match_vip: enable
      srcaddr_negate: disable
      dstaddr_negate: disable
      service_negate: disable
      captive_portal_exempt: disable
