---
- name: Create OB-ALLOW-DNS-NTP-to-wan policy
  fortios_firewall_policy:
    access_token: '{{ api_key }}'
    state: present
    vdom:  '{{ vdom }}'
    firewall_policy:
      policyid: 60
      name: OB-ALLOW-DNS-NTP-to-wan
      status: enable
      srcintf:
        - name: z-trust
        - name: z-untrust
      dstintf:
        - name: z-wan
      action: accept
      srcaddr:
        - name: all
      dstaddr:
        - name: AG-PRIVATE-ADDRESSES
      internet_service: disable
      internet_service_src: disable
      schedule: always
      service: 
        - name: DNS
        - name: NTP
      utm_status: enable
      inspection_mode: flow
      profile_type: single
      profile_protocol_options: default
      ssl_ssh_profile: certificate-inspection
      av_profile: default
      ips_sensor: dns-outbound
      logtraffic: all
      auto_asic_offload: enable
      np_acceleration: enable
      nat: enable
      srcaddr_negate: disable
      dstaddr_negate: enable
      service_negate: disable
      timeout_send_rst: disable
      captive_portal_exempt: disable
