---
- name: Install ADDS
  hosts: windows_servers
  collections:
    - microsoft.ad
    - ansible.windows
  tasks:
    - name: Create folders
      import_tasks: tasks/create-folders.yml

    - name: Create shares
      import_tasks: tasks/create-shares.yml
