---
- name: Configure WAN interface for PPPoE
  fortios_system_interface:
    access_token: '{{ api_key }}'
    state: present
    vdom: '{{ vdom }}'
    system_interface:
      alias: WAN-Uplink-PPPoE
      allowaccess:
        - fgfm
        - https
        - ping
        - snmp
        - ssh
      device_identification: enable
      egress_shaping_profile: 'Outgoing Shaping'
      estimated_downstream_bandwidth: '{{ estimated_down_kbps }}'
      estimated_upstream_bandwidth: '{{ estimated_up_kbps }}'
      interface: '{{ wan_interface_name }}'
      mode: pppoe
      name: '{{ wan_interface_name_pppoe }}'
      outbandwidth: '{{ estimated_up_kbps }}'
      password: '{{ pppoe_password }}'
      role: wan
      username: '{{ pppoe_username }}'
      vdom: '{{ vdom }}'
      vlanid: '{{ wan_vlan }}'
