---
- name: Configure VoIP Network
  fortios_system_interface:
    access_token: '{{ api_key }}'
    state: present
    vdom: '{{ vdom }}'
    system_interface:
      allowaccess:
        - ping
      arpforward: enable
      device_identification: enable
      device_user_identification: enable
      interface: '{{ lan_interface_name }}'
      ip: '{{ voip_gateway_address }} {{ voip_netmask }}'
      mode: static
      name: '{{ voip_interface_name }}'
      role: lan
      src_check: enable
      status: down
      type: vlan
      vdom: '{{ vdom }}'
      vlan_protocol: 8021q
      vlanid: '{{ voip_vlan }}'
