---
- name: Configure LAN Network
  fortios_system_interface:
    access_token: '{{ api_key }}'
    state: present
    vdom: '{{ vdom }}'
    system_interface:
      allowaccess:
        - fgfm
        - http
        - https
        - ping
        - snmp
        - ssh
      device_identification: enable
      device_user_identification: enable
      ip: '{{ lan_gateway_address }} {{ lan_netmask }}'
      mode: static
      mtu_override: disable
      name: '{{ lan_interface_name }}'
      role: lan
      status: up
      stp: enable
      vdom: '{{ vdom }}'
