dns_records:
  - name: mgc-drw-hvs01
    type: A
    value: 192.168.1.17
    state: present
  - name: mgc-drw-hvs02
    type: A
    value: 192.168.1.16
    state: present
  - name: mgc-drw-hvs03
    type: A
    value: 192.168.1.15
    state: present
  - name: mgc-drw-hvs04
    type: A
    value: 192.168.1.18
    state: present
