# Use FQDN for kerberos authentication
ansible_host: mgc-drw-dmc01.prod.megacorp.industries

ansible_password: '{{ vault_ansible_password }}'
hostname: MGC-DRW-DMC01

# Domain Settings
domain_admin_password: '{{ vault_domain_admin_password }}'
safe_mode_password: '{{ vault_safe_mode_password }}'
windows_domain_name: prod.megacorp.industries
windows_netbios_name: PROD
base_dn: dc=prod,dc=megacorp,dc=industries
company_shortcode: MGC

create_linux_ou: true

users_system_admins:
  - firstname: Ben
    lastname: Harris
    username: ben.harris
    display_name: Ben Harris

users_hr:
  - firstname: Kristin
    lastname: Cabot 
    username: kristin.cabot
    display_name: Kristin Cabot

dns_records:
  - name: mgc-drw-hvs01
    type: A
    value: 192.168.1.17
  - name: mgc-drw-hvs02
    type: A
    value: 192.168.1.16
  - name: mgc-drw-hvs03
    type: A
    value: 192.168.1.15
  - name: mgc-drw-hvs04
    type: A
    value: 192.168.1.18
